[package]
name = "index"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isahc = "1.5.0"
regex = "1"

[dependencies.pyo3]
version = "0.14.5"
features = ["auto-initialize"]
